### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by yevhenmanaienkov** [ita-social-projects/Home#2]
**As a** owner or developer **I want to** have database design  **so that** I can plan how to store my primary data.

**Description**
Design and implement the main database without delving into the additional capabilities of the service.

### Acceptance Criteria
Database schema ready for implementation.

### Tasks 
1. - [ ] Design database scheme.
2. - [ ] Move database scheme to common documentation.

**Comment by kh0ma** [comment]
We will be using API first approach. I don't think this story is relevant.
