### ISSUE TITLE
Manage votes on polls

### ISSUE THREAD

**Issue by tex1988** [ita-social-projects/Home#229]
As a developer i want to have an ability to manage (create) votes on poll

### Description
Add ability to:
- create vote (Vote can be created only if poll status is active. Number of answers must be validated according to max_answer_count of the question)

Implement:
- all necessary entities for creating votes (vote, question vote, etc)
- changes for existing entities connected with votes (poll, etc)
- liquibase scripts to update database with tables and data required for new entities
- all necessary repositories to manage votes
- all necessary services to manage  votes
- controllers (api implementation)  to manage votes using existing API interfaces
- all necessary tests to check new functionality

Follow the [design](https://github.com/ita-social-projects/Home/pull/223)

Epic #162
[ZenHub Epic](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/162)

### Acceptance Criteria
Ability to manage (create) votes on poll

**Comment by klaeck** [comment]
Entity relation (pools lifecycle) diagram needed.
