### ISSUE TITLE
Manage poll results

### ISSUE THREAD

**Issue by tex1988** [ita-social-projects/Home#230]
As a developer i want to have an ability to manage (get) polls results

### Description
Add ability to:
- get poll result of current poll (Ability to get poll result is aviable only if poll status is completed) 

Implement:
- all necessary entities for getting poll result (poll result, question result, etc)
- changes for existing entities connected poll results (poll, etc)
- liquibase scripts to update database with tables and data required for new entities
- all necessary repositories to manage poll results
- all necessary services to manage poll results
- controllers (api implementation)  to manage poll results using existing API interfaces
- all necessary tests to check new functionality

Follow the [design](https://github.com/ita-social-projects/Home/pull/223)

Epic #162
[ZenHub Epic](https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/162)

### Acceptance Criteria
Ability to manage (get) polls results

**Comment by gendalf-fx** [comment]
Already closed
