### ISSUE TITLE
Versioning of HOME application

### ISSUE THREAD

**Issue by VadymSokorenko** [ita-social-projects/Home#236]
Research on existing versioning approaches. Choose the most relevant to be used in HOME project.
Consider including changelog to application and using automation tools for versioning.

**Comment by Vladyslav-Frolov** [comment]
After conducting research, it was found that the best version control occurs using the semantic versioning convention. Further, our versions can be saved in our internal file and selected versions can be published on github in the section https://github.com/** / releases of our project. To do this, we need to mark the commit that we want to publish as a version with a git tag indicating the version by semver convention (this can be done both during or after creating the commit) and in the versions section of github publish our commit as a version with linked to the commit. Github also provides the ability to add a tag during the publication of the version during the binding of the commit. Further research has been done on automating this approach, and no library does versioning automation with publishing on github with teamwork in mind. All libraries assume that one person works and simply increment the version by the semver convention. Therefore, it is advisable to create your own console application to create the correct commit with a tag and maintain versioning in a separate file for the purposes of the command, and the responsible person must manually publish the commits selected by the team as a version on the github. It is also desirable to immediately associate versioning with a commit convention, which is created on the basis of a versioning agreement. For the purpose of creating a console application, a separate task will be opened. 

Useful links below.
1) Semantic Versioning 2.0.0 → [link](https://semver.org/)
2) Conventional Commits → [link](https://www.conventionalcommits.org/en/v1.0.0/)
3) Managing releases in a repository (docs.github.com) → [link](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository)
