### ISSUE TITLE
Functional Demo preparation

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#239]
Prepare a demonstration to cover all the functionality that is currently implemented in the application in order to put our BA/PO into the picture of the current state.

**Comment by likeRewca** [comment]
A video with a Functional Demo recording is in the google dock of our project for 06/15/2021.
Also presentation - https://docs.google.com/presentation/d/16qzJTiOe-GMKbimeHoYQSeg5MkEkWKHbytg2QVZXtwU/edit?usp=sharing
