### ISSUE TITLE
Define Roles and prepare Role Matrix

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#241]
In order to refactor our Authorization, we have to work on defining User Roles that will be used in the system and prepare Role Matrix for the existing actions.

**Comment by AriannaLiss** [comment]
Role Matrix at google disk [Home/Project descriptions/Role Matrix](https://docs.google.com/spreadsheets/d/1kKI9s_mpG3x30oWkVwgl34n7tnQsx3QgsDiI61fYJvo/edit?usp=sharing)
In our project Role Matrix located in home-docs/role-matrix.md
