### ISSUE TITLE
Investigate options to add auditing into the application

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#242]
In order to control changes among the data in the application, we have to have history. Please research existing approaches to accomplish it in our application.

**Comment by veniamin-aveltsev** [comment]
[https://app.zenhub.com/files/298601645/48ab20d7-c5b8-4897-96a0-9755510637dc/download](https://app.zenhub.com/files/298601645/48ab20d7-c5b8-4897-96a0-9755510637dc/download)
