### ISSUE TITLE
Fix default examples and models

### ISSUE THREAD

**Issue by AriannaLiss** [ita-social-projects/Home#247]
*Fix default models and examples for creating/updating users, cooperations etc.*

**As an** admin **I want to** have correct examples for creating and updating users, cooperation etc. 

**Description**
When I want to create a user the first time I recieve an error with response status 400:
"Missing type id when trying to resolve subtype of [simple type, class com.softserveinc.ita.homeproject.model.CreateContact]: missing type id property 'type' (for POJO property 'contacts')
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 12, column: 5] (through reference chain: java.util.ArrayList[1])"

*By default example for creating user looks like that:*
 {
  "first_name": "Petro",
  "last_name": "Zinchenko",
  "email": "p.t.z@gmail.com",
  "password": "mySuperStrongPass",
  "contacts": [
    {
      "type": "email"
    },
    {
      "id": 1
    },
    {
      "main": false
    },
    {
      "email": "createUserEmail@example.com"
    }
  ]
} 

There is a problem with contacts example here.
*I want the example of contact for creation a user looks like this:*
"contacts": [
    {
      "type": "email",
      "main": false,
      "email": "createUserEmail@example.com"
    }

*Similar problem with creating new contact for user and cooperation, updating contact, creating cooperation (wrong contacts and houses examples).*

### Acceptance Criteria
All existing endpoints work with default example of sturcture json for a request body.

**Comment by Vladyslav-Frolov** [comment]
2021/06/19 → I found that an error occurs when auto-generating examples from the yaml file. For this reason, it is not enough just to correct the examples, but to understand why the generation of examples is incorrect.

**Comment by Vladyslav-Frolov** [comment]
2021/07/13 → added new approach to writing examples in Jason format instead of YAML
