### ISSUE TITLE
Fix exception message in polls

### ISSUE THREAD

**Issue by AriannaLiss** [ita-social-projects/Home#250]
When I create get query for /polls without cooperation_id I receive this answer:
{
  "response_code": 400,
  "error_message": "Parameter `arg0` is invalid - must not be null."
}

When I run test I recieve message:
"Missing the required parameter 'cooperationId' when calling queryPoll"
It is send by home-clients/target/generated-sources/openapi/client/src/gen/java/main/com/softserveinc/ita/homeproject/api/PollApi.java but shouldn't be send because in this case my test is invalid.

It's necessary to show name of parameter 'cooperation_id' in error_message. It should be:
{
  "response_code": 400,
  "error_message": "Parameter `cooperation_id` is invalid - must not be null."
}

And the same in the test.

**Comment by kizimov** [comment]
https://github.com/ita-social-projects/Home/pull/262
