### ISSUE TITLE
Extend user creation with invite tokens

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#256]
As a potential user of our application I want to have an ability to registrate using invite token and get enough rights to be able to use the application within granted cooperation.

### Description
Add ability to:
- use provided token when registrate user. This new field must be mandatory so it will be impossible to registrate w/o the invite token.

Implement:
- changes to existing entities (user, etc)
- liquibase scripts to update database with data required
- all necessary tests to check new functionality

### Acceptance Criteria
Newly registered user has roles/authorities only within given cooperation.

**Comment by likeRewca** [comment]
How token will be provided to user?

**Comment by kh0ma** [comment]
> How token will be provided to user?

It is already provided via invitation email.
