### ISSUE TITLE
Create a checklist with all the stages of the development and versioning process and include it in our README.md file (ref issue #252)

### ISSUE THREAD

**Issue by Vladyslav-Frolov** [ita-social-projects/Home#275]
Create a readme in a separate one .md file and give a link to it in the file readme.md

**Comment by Vladyslav-Frolov** [comment]
Link on presentation in Slack "Versioning for developing commercial applications" → link

**Comment by kh0ma** [comment]
We decided to kick it out from sprint because this issue is blocked by #274
