### ISSUE TITLE
Fix flaky test for CI of CooperationPollApiIT

### ISSUE THREAD

**Issue by Vladyslav-Frolov** [ita-social-projects/Home#277]
When there is a build on CI (github actions → jobs → build), the CooperationPollApiIT test is unstable. It can work out, or it can fall. This is not convenient in the current development, and in the future it can critically take away precious time. This problem should be fixed at the stage when the project is not very large.

![2021-07-12_10-16-26.jpg](https://images.zenhubusercontent.com/606319632f2b7b6f148afe64/2fab917f-fcfc-4372-87d0-d96d09559907)![photo_2021-07-12_10-12-19.jpg](https://images.zenhubusercontent.com/606319632f2b7b6f148afe64/f540ac2d-5ef5-40ab-ac81-952233ae6175)![photo_2021-07-12_10-15-12.jpg](https://images.zenhubusercontent.com/606319632f2b7b6f148afe64/a84912ce-8c36-400c-a216-ff110cb65926)![photo_2021-07-12_10-15-31.jpg](https://images.zenhubusercontent.com/606319632f2b7b6f148afe64/1044c6f2-a87e-4ad0-aa43-e197039b4957)

**Comment by kh0ma** [comment]
Why is it in IceBox? Is it still an issue?
