### ISSUE TITLE
Organize packages by domain

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#285]
**As a** home project developer **I want to** have our classes be placed in packages that are organized by the domain area so it will be easier to distinguish one feature from another.

### Description
Consider known best practices in organizing java packages (e.g. [Package by feature, not layer](http://www.javapractices.com/topic/TopicAction.do?Id=205)) please organize our packages by domain area so we will still have modules splitter by layer and packages inside module splitter by domain area.

For example:

`com.softserveinc.ita.homeproject.homedata.entity` ->

- `com.softserveinc.ita.homeproject.homedata.entity.user`
- `com.softserveinc.ita.homeproject.homedata.entity.poll`
- `com.softserveinc.ita.homeproject.homedata.entity.cooperation`
- etc.

Affected modules: home-data, home-service, home-application

### Acceptance Criteria
We still have our application organized by layers using modules and our modules organized by domain area using packages.

**Comment by Vladyslav-Frolov** [comment]
New introductory notes for your task, you should consider creating folders on the following domain area:

User → Ownership, User_cooperation, Permission, Role
Poll → templates (+ answer), voting (+result), questions
Cooperation → houses, apartments, invitations
General → address, news, contacts

* base entity → preferably should be at the root
* think about security and config (they can be define in a separate folder only in the home-application)
