### ISSUE TITLE
Implementing Quartz-Actuator

### ISSUE THREAD

**Issue by Illia-Shchur** [ita-social-projects/Home#293]
As a developer i want to run tests quickly. In tests where we are using our jobs we need to configure their cron time.
(https://github.com/Home-Project-Engineering/quartz-actuator). 

Quart-actuator has client package wich you can use as api solution to use it in our tests.

**Comment by vladyslavyarets** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/293?planning-poker) with ZenHub @EkaterinaYatsyna @gendalf-fx @paulspam @varhanovdm
