### ISSUE TITLE
Write tests for methods not covered by tests in the ApartmentApiImpl controller

### ISSUE THREAD

**Issue by Vladyslav-Frolov** [ita-social-projects/Home#300]
the group of methods associated with the invitations is not covered by tests, namely:
1) createInvitation
2) getInvitation
3) queryInvitation

the problem is temporarily blocked because not all methods of the specified methods work correctly, first you need to make the methods work correctly by solvation issue #299

**Comment by EkaterinaYatsyna** [comment]
the task is irrelevant because it was completed in another tasks - 
https://app.zenhub.com/workspaces/home-project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/home/361
