### ISSUE TITLE
Rewrite the tests for getting rid of the sql script file

### ISSUE THREAD

**Issue by Vladyslav-Frolov** [ita-social-projects/Home#303]
Rewrite the tests so that the test_script.sql file is no longer needed in our home-api-tests modules

**Comment by Vladyslav-Frolov** [comment]
rewrite the tests so that the test_script.sql file is no longer needed in our home-api-tests modules

**Comment by posabogdanpetre** [comment]
@Vladyslav-Frolov I would like to work on this.
