### ISSUE TITLE
Template download feature

### ISSUE THREAD

**Issue by klaeck** [ita-social-projects/Home#305]
For data import in the system required .xlsx template file. Create template strict to the following example https://home-project-engineering.atlassian.net/jira/software/projects/HP/boards/1/backlog?selectedIssue=HP-11. Implement functionality to download this template from application.

**Comment by vladyslavyarets** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/305?planning-poker) with ZenHub @EkaterinaYatsyna @gendalf-fx @paulspam @varhanovdm

**Comment by vladyslavyarets** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/305?planning-poker) with ZenHub @VladyslavZhigir

**Comment by vladyslavyarets** [comment]
Done
