### ISSUE TITLE
Create resource pool for tests

### ISSUE THREAD

**Issue by klaeck** [ita-social-projects/Home#307]

**Comment by EkaterinaYatsyna** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/307?planning-poker) with ZenHub @BohdanLysenko @Sorex1992 @VladyslavZhigir

**Comment by EkaterinaYatsyna** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/307?planning-poker) with ZenHub @varhanovdm

**Comment by gendalf-fx** [comment]
Task was closed due to lack of the information.
