### ISSUE TITLE
Fix the problem with adding appartment to the house

### ISSUE THREAD

**Issue by SerhiiPakulia** [ita-social-projects/Home#313]
### Description

We need to fix the bug when we add several apartments with the same number and add validation for the name of the apartment number (should be without spaces). At the moment, we can add to the house two apartments with the same number. 

### Acceptance Criteria

Write a validation for this problem and also tests covering this validation.

**Comment by ghost** [comment]
can you explain me what is the bug?

**Comment by SerhiiPakulia** [comment]
A house should not have several apartments with the same number.

**Comment by satyamsettyeswara** [comment]
Hi, I want to work on this. can someone help me? I installed everything but had some problem with application it is asking API key
![image](https://user-images.githubusercontent.com/31738585/134497056-78db00c2-c7ac-4e5f-b78d-23d9371f949c.png)

**Comment by bbogdasha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/313?planning-poker) with ZenHub @kizimov @klaeck @SerhiiPakulia

**Comment by bbogdasha** [comment]
In localhost use this credits:
Username: admin@example.com
Password: password
