### ISSUE TITLE
Fixing bugs with cooperation registration flow

### ISSUE THREAD

**Issue by klaeck** [ita-social-projects/Home#321]

**Comment by bbogdasha** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/321?planning-poker) with ZenHub @SerhiiPakulia

**Comment by bbogdasha** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/321?planning-poker) with ZenHub @OliMpiX
