### ISSUE TITLE
Add middle name to User model

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#324]
As part of the business request, we have to add 'middle_name' to `User` model so the User will be able to provide the middle name on the registration and update it.

**Requirements:**
- add 'middle_name' to 
   - ReadUser model
   - CreateUser model
   - UpdateUser model
- 'middle_name' must be mandatory so it isn't allowed to provide `null`, blank or empty strings
- add a query parameter 'middle_name' to `/users` endpoint

**Acceptance criteria:**
- User is able to provide/change/read the middle name from API
- It is possible to search users by middle name

**Comment by SerhiiPakulia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/324?planning-poker) with ZenHub @bbogdasha @OliMpiX
