### ISSUE TITLE
Add support of Swagger UI and ReDoc openapi viewers

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#326]
In order to provide a better experience of viewing our API docs, as well as giving a freedom of choice please add Swagger UI and ReDoc in addition to the RapiDoc.

**Requirements:**
- new tools must be added to `/api/0/apidocs/index.html` the same way as RepiDoc currently added so users can decide which tool to use, e.g.:
![image.png](https://images.zenhubusercontent.com/5f7b73516450e01e28e9899e/0f4595ee-482b-4f33-a20f-6325f9e1c456)
- the same approach of managing version through webjars must be utilized

**Acceptence:**
- new viewers added

**Dev notes:**
Html from screenshot - 
```html
<style>
    a {
        text-decoration: none;
    }
</style>

<h1 style="text-align:center">&nbsp;</h1>

<p style="text-align:center; font-size: 32px">You can read our api docs by preferable openapi spec viewer:</p>

<p style="height:96px;text-align:center"><a href="/swagger-ui.html"><span style="color:#000000"><img alt="logo"
        src="https://avatars.githubusercontent.com/u/7658037?s=280&amp;v=4"
        style="height:96px; width:96px; vertical-align:middle"/><span style="font-size:48px; vertical-align:middle">Swagger UI</span></span></a>
</p>

<p style="text-align:center">&nbsp;</p>

<p style="text-align:center"><a href="rapidoc.html"><img alt="logo"
                                                         src="https://github.com/mrin9/RapiDoc/blob/master/logo.png?raw=true"/>&nbsp;<span
        style="font-size:48px"><span style="color:#27ae60">Ra</span><span style="color:#f1c40f">pi</span><span
        style="color:#f39c12">doc</span></span></a></p>

<p style="text-align:center">&nbsp;</p>

<p style="text-align:center"><a href="/redoc.html"><img
        alt="ReDoc"
        src="https://raw.githubusercontent.com/Redocly/redoc/master/docs/images/redoc-logo.png"
        style="height:81px; width:250px"/></a></p>

<p style="text-align:center">&nbsp;</p>
```

**Comment by SerhiiPakulia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/326?planning-poker) with ZenHub @bbogdasha @OliMpiX
