### ISSUE TITLE
Remove 'ownership_part' from ApartmentInvitation

### ISSUE THREAD

**Issue by bbogdasha** [ita-social-projects/Home#334]
### Description

We need to remove the 'ownership_part' parameter in Apartments invitation and all validation. We must set 'ownership_part' to zero when we create an invitation to an apartment.

### Acceptance Criteria

Delete or change the validation and the tests covering these changes.

**Comment by SerhiiPakulia** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/334?planning-poker) with ZenHub @OliMpiX
