### ISSUE TITLE
Remove email and password from UpdateUser payload

### ISSUE THREAD

**Issue by kh0ma** [ita-social-projects/Home#336]
As part of the business request, we have to have only name fields updateable for User model. Please remove email and password from it.

**Requirements:**
- remove 'password' and 'email' from 
   - UpdateUser model

**Acceptance criteria:**
- User is able to be updated w/o specifying email+password
- email+password aren't updateable from edit user action

**Comment by bbogdasha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/336?planning-poker) with ZenHub @EkaterinaYatsyna @Sorex1992 @varhanovdm @VladyslavZhigir
