### ISSUE TITLE
Create version endpoint

### ISSUE THREAD

**Issue by bbogdasha** [ita-social-projects/Home#341]
### Description

We need to add a new endpoint '_version_', which will return us json information

For example, if I want to see the current version of the product, I need to get to this point "www.home-project-engineering.tech/api/0/apidocs/**version**"
And I should get this message:

``` json
{
  "version": "1.0.1-1",
  "build_number": "1",
  "build_date": "10/10/2021"
}
```

**Comment by Pavlo-Ponomarenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/341?planning-poker) with ZenHub @bbogdasha @varhanovdm

**Comment by Pavlo-Ponomarenko** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/341?planning-poker) with ZenHub @lawalina

**Comment by bbogdasha** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/341?planning-poker) with ZenHub @lawalina
