### ISSUE TITLE
Refactoring Maven

### ISSUE THREAD

**Issue by EkaterinaYatsyna** [ita-social-projects/Home#362]
### Description:

It is necessary to review all maven files in the following steps:

1. It is necessary to check for unused dependencies in the project and remove them;
2. It is necessary to review the versions of plugins and dependencies (using Dependency Management in the root maven file);
3. Logically group the contents of the maven files.

### Acceptance criteria:

For more information about the criteria of maven file structure you can see here: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by bbogdasha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/362?planning-poker) with ZenHub @EkaterinaYatsyna @Sorex1992 @varhanovdm @VladyslavZhigir

**Comment by kh0ma** [comment]
Even if you guys properly groomed this ticket it isn't OK to leave it w/o a description. It can be historically valuable to understand what was done as part of it. Please add a description with requirements and acceptance criteria.

CC: @MrScors

**Comment by bbogdasha** [comment]
@kh0ma , Done!
Understood my mistake, we will open tasks along with a description of the requirements.
