### ISSUE TITLE
Add transaction in git action

### ISSUE THREAD

**Issue by EkaterinaYatsyna** [ita-social-projects/Home#363]
### Description:

During the build process, a failure may occur or one of the services (DockerHub or GitHub packages) may not be available. 

The CD (or Build_and_deploy_workflow.yml file) should be able to not make changes if something has gone wrong. In other words, add a transaction to the project build process at GitHub actions. 

### Acceptance criteria:

Test writing is not required

**Comment by bbogdasha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/363?planning-poker) with ZenHub @EkaterinaYatsyna @Sorex1992 @varhanovdm @VladyslavZhigir
