### ISSUE TITLE
Realize OAuth 2 and resource server 

### ISSUE THREAD

**Issue by EkaterinaYatsyna** [ita-social-projects/Home#364]
Add authorization server

Refactor resource server:
- Create endpoints to logout from device/all devices.(expire all tokens by user id).

Create Quartz job to clean DB from expired access/refresh tokens:
- Once a day we need to clean row with expired access/refresh tokens.

**Comment by bbogdasha** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/364?planning-poker) with ZenHub @EkaterinaYatsyna @Sorex1992 @varhanovdm @VladyslavZhigir

**Comment by gendalf-fx** [comment]
Can`t be closed in the 37th sprint because of changes in production code, fail api-tests.
Required changes:
- set bearer token instead of basic authorization

**Comment by gendalf-fx** [comment]
Generate OauthApiClient from openapi specification in order to get authentication for api-tests.
