### ISSUE TITLE
ModelMapper converting issue

### ISSUE THREAD

**Issue by VladyslavZhigir** [ita-social-projects/Home#377]
Problem with convert  from CreateInvitation.class to ApartmentInvitationDto.class and CooperationInvitationDto. 
Example 
 mapper.convert(createInvitation, ApartmentInvitationDto.class);
mapper.convert(createInvitation, CooperationInvitationDto.class);

when we try to convert createInvitation instance to ApartmentInvitationDto or CooperationInvitationDto
modelMapper sets Apartment ID or Cooperation ID in field ID.

**Comment by vladyslavyarets** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/377?planning-poker) with ZenHub @gendalf-fx @paulspam @varhanovdm @VladyslavZhigir
