### ISSUE TITLE
Create class for error messages 

### ISSUE THREAD

**Issue by VladyslavZhigir** [ita-social-projects/Home#388]
move all static variables to the one static class

**Comment by SimosNeopoulos** [comment]
Can you please specify what from witch classes you want the static veriables to be removed and which one is the class you want them moved to?

**Comment by vladyslavyarets** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/388?planning-poker) with ZenHub @gendalf-fx @paulspam @varhanovdm @EkaterinaYatsyna

**Comment by vladyslavyarets** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/388?planning-poker) with ZenHub @VladyslavZhigir

**Comment by vladyslavyarets** [comment]
Done
