### ISSUE TITLE
Update Poll Functionality change request

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#391]
As a cooperation admin I want to be able to update the poll with the following parameters:
**Poll can be update only when its start_date is in future**

- title (header)
- description
- list of included houses
- start date (only in case the current start date is in the future)

**changes required from back-end team:**

For endpoint **PUT cooperations/{cooperation_id}/polls/{id}**

- add a **description** field to the request body, 
- add **start_date** field,
- add **included_houses** field,
- remove **completion_date** field, 
- remove **status** field

**Comment by gendalf-fx** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/391?planning-poker) with ZenHub @BohdanLysenko

**Comment by BohdanLysenko** [comment]
We need to keep "status" for update 
If user wants to change status to active we should change start_date to local timestamp
