### ISSUE TITLE
View List of Polls Functionality change request

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#392]
As a cooperation admin I want to be able to view the poll list, each poll in which should have the following parameters:
- title (header)
- description
- list of included houses
- start date
- end date

**changes required from back-end team:**

For endpoint **GET cooperations/{cooperation_id}/polls**

- add a **description** field to the request body
- remove **status** field

**Comment by gendalf-fx** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/392?planning-poker) with ZenHub @BohdanLysenko
