### ISSUE TITLE
Poll Result Calculation

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#404]
- Add column **RESULT** to the POLL table in the database

- Add field **result** to the response body of **/cooperations/{cooperation_id}/polls**

- The Result field should contain % of positive responses if the ownership part of any owner is 50% or more, count the number of votes, otherwise, count **HOUSE_OWNERSHIP_PART** (sum of ownership part * area of the apartment for each of his apartments)

- Whenever used call **/cooperations/{cooperation_id}/polls** we have to iterate all over polls, if completion data in past, set the corresponding status, calculate and save to the DB **RESULT** field if it is null

**Comment by BohdanLysenko** [comment]
can we discuss that on Friday?
