### ISSUE TITLE
Able to create Vote for Poll wihch is outdated

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#408]
Update VoteServiceImpl.java createVote() method logic
to remove the ability of users to vote for outdated Votes
Cover this logic with Unit tests

**Comment by gendalf-fx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/408?planning-poker) with ZenHub @vladyslavyarets @varhanovdm @VadimHolder
