### ISSUE TITLE
Rewrite All Models usage to initialize with @Builder instead of Cunstructors and Setters

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#409]
To rewrite model add @Builder annotation to it, search for all usages of its constructors and setters in code and if possible to replace that with builder() method usage on the class name, also if no usages of model's constructors are found, remove @AllArgsConstructors and @NoArgsConstructor annotations from it

**Comment by gendalf-fx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/409?planning-poker) with ZenHub @VadimHolder @varhanovdm @vladyslavyarets

**Comment by vladyslavyarets** [comment]
Task was closed due to unable use @Builder with current implementation. There is mapped exception causes absence of non-private no-args constructor.
