### ISSUE TITLE
Create backup of data from heroku database into CSV files

### ISSUE THREAD

**Issue by gendalf-fx** [ita-social-projects/Home#413]

**Comment by gendalf-fx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/413?planning-poker) with ZenHub @VadimHolder @varhanovdm @vladyslavyarets

**Comment by vladyslavyarets** [comment]
Closed due to emptiness of changed table on Heroku
