### ISSUE TITLE
Refactor Service implementation layer with new database structure

### ISSUE THREAD

**Issue by gendalf-fx** [ita-social-projects/Home#416]
Rewrite entities, dtos and service implementations of: 
Poll, Question, Results, Votes.

Implement all TODOs from issue412.xml in the new changeset script.

**Comment by gendalf-fx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/416?planning-poker) with ZenHub @VadimHolder @lEquinoXl @varhanovdm

**Comment by gendalf-fx** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/416?planning-poker) with ZenHub @vladyslavyarets

**Comment by gendalf-fx** [comment]
Can`t be closed because of minor implementation changes in service layer(Poll calculation functionality).

**Comment by vladyslavyarets** [comment]
Closed due to emptiness of changed table on Heroku
