### ISSUE TITLE
Import data from backup

### ISSUE THREAD

**Issue by gendalf-fx** [ita-social-projects/Home#417]
Import data from CSV files to the new database structure.
Create ChangeSet to remove all tables and columns related on previous version of database.

**Comment by gendalf-fx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/417?planning-poker) with ZenHub @VadimHolder @vladyslavyarets @lEquinoXl

**Comment by vladyslavyarets** [comment]
Closed due to emptiness of changed table on Heroku
