### ISSUE TITLE
Replace all var key words usages with Class\Interface names

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#419]
Go through the whole project and replace all **var** key words usages with Class\Interface names

**Comment by gendalf-fx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/419?planning-poker) with ZenHub @lEquinoXl @VadimHolder @vladyslavyarets @varhanovdm
