### ISSUE TITLE
Invitations section address missing issue

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#441]
![image.png](https://images.zenhubusercontent.com/619c94788c359400ac3345aa/ca6321c7-90dc-4490-9916-44d229e9ba3c)

`curl 'https://home-project-academy.herokuapp.com/api/0/invitations?type=apartment' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxMDAyIiwic3ViIjoieS5kLmRldmJveEBnbWFpbC5jb20iLCJpYXQiOjE2NTY1MDQyNDEsImV4cCI6MTY1NjU5MDY0MX0.-LlD40agG9UPwMqV_xrw5u7qMNL1ARj6DTA3_JOZADlshZ4cB4Nw7n2-sFiseWbJbySTGURgHjNSgVQ7iNGi2A' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:8080' \
  -H 'Referer: http://localhost:8080/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed`

Actual: address field is missing inside the apartment entity 
Expected: address field should be present within the apartment entity as documented in openapi

**Comment by MrScors** [comment]
![image.png](https://images.zenhubusercontent.com/619c94788c359400ac3345aa/ca6321c7-90dc-4490-9916-44d229e9ba3c)

`curl 'https://home-project-academy.herokuapp.com/api/0/invitations?type=apartment' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxMDAyIiwic3ViIjoieS5kLmRldmJveEBnbWFpbC5jb20iLCJpYXQiOjE2NTY1MDQyNDEsImV4cCI6MTY1NjU5MDY0MX0.-LlD40agG9UPwMqV_xrw5u7qMNL1ARj6DTA3_JOZADlshZ4cB4Nw7n2-sFiseWbJbySTGURgHjNSgVQ7iNGi2A' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:8080' \
  -H 'Referer: http://localhost:8080/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed`

Actual: address field is missing inside the apartment entity 
Expected: address field should be present within the apartment entity as documented in openapi

**Comment by vladyslavyarets** [comment]
Done
