### ISSUE TITLE
Add password complexity validation

### ISSUE THREAD

**Issue by vladyslavyarets** [ita-social-projects/Home#449]
Needed to write business logic for password complexity validation in user registration step.

**Preconditions**:
- minimum length: 8 symbols
- Latin capital letters
- Latin small letters
- Non-letter symbols

**Error path response**:
- response_code: HTTP 406 (Not Acceptable) 
- error_message: "Password too weak"

**Comment by kvaithin** [comment]
Hi, where does this user registration step occur?

**Comment by vladyslavyarets** [comment]
home-service module, UserServiceImpl.java. Presumably 98th line. Consider to write it for further usability this functionality from other places of the application (See task #451)

**Comment by vladyslavyarets** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/449?planning-poker) with ZenHub @paulspam

**Comment by vladyslavyarets** [comment]
Correct Pull Request link: https://github.com/ita-social-projects/Home/pull/462
