### ISSUE TITLE
Registration link in the invitation is still pointing to Swagger

### ISSUE THREAD

**Issue by MrScors** [ita-social-projects/Home#463]
Actual: While creating new cooperation the registration link is pointing to Swagger
Expected: While creating new cooperation the registration link should lead to UI as was described at #444 ticket

**Comment by MrScors** [comment]
@vladyslavyarets please look into this issue and add appropriate assignee

**Comment by vladyslavyarets** [comment]
This works only for links for new user registration. That's what UI team asked about. For existed user which wants to create another one cooperation there's was out of scope. They gives as only one link which was uploaded.

**Comment by vladyslavyarets** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/463?planning-poker) with ZenHub @gendalf-fx @paulspam @ystoikov @EkaterinaYatsyna

**Comment by vladyslavyarets** [comment]
Add generated link e.g. ```https://home-project-ui.herokuapp.com/register-cooperation?email=mailbox@example.com&token=f8e20775-da55-11eb-a58d-775374b8f3a1```

Refactor and reuse existing method ```getRegistrationLink()``` form ```BaseEmailService``` for this

**Comment by vladyslavyarets** [comment]
Done
