### ISSUE TITLE
Create authentication entry point to handle exceptions while filters validation chain

### ISSUE THREAD

**Issue by gendalf-fx** [ita-social-projects/Home#470]

**Comment by gendalf-fx** [comment]
Now we have custom interceptor only for one Exception type NotAcceptableOauthException. 
In order to handle all the types of Authentication exceptions we need to implement AuthenticaionEntryPoint in our security configuration. 

![image.png](https://images.zenhubusercontent.com/61ea703185989501f7430a84/e2d389cc-a4f4-4194-91c0-bb09f8c06e3b)

**Comment by vladyslavyarets** [comment]
Not actual.
