### ISSUE TITLE
Release testing instance of application

### ISSUE THREAD

**Issue by vladyslavyarets** [ita-social-projects/Home#482]
#### Overview

For correct synchronization between front-end and back-end teams after changing specification for apartment and user registration there required instance of application with stabbed logic. After implementing tasks #480 and #481. Build the container with correct working application and deploy to the heroku.

#### Tasks

1. Merge result of implementing of features in the tasks #480 and #481 into the one branch.
2. Check the happy path logic for avoiding violations
3. Build the project locally for creating image with application
4. Deploy an instance of application to heroku with name ```home-application-test```. Deploy process described in ```home-dev/home-application-heroku-deploy.md```

**Comment by vladyslavyarets** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Home-Project-5f7b77ff8db73a001cb17009/issues/ita-social-projects/Home/482?planning-poker) with ZenHub @artmarchenko @gendalf-fx @ystoikov

**Comment by vladyslavyarets** [comment]
For working on this task was created new branch called ```feature/Issue#482-Release-testing-instance-of-application```. Pull the new branch and don't create new one.

**Comment by artmarchenko** [comment]
Done!
