### ISSUE TITLE
Github Pages Migration

### ISSUE THREAD

**Issue by yevhenmanaienkov** [ita-social-projects/Home#7]
**As a** owner or any person interested in the project **I want to** be able to view all project details on Github pages **so that** me and all outside world can get the latest information about project in a good way.

**Description**
Using https://pages.github.com/, transfer all project documents to GitHub pages.

### Acceptance Criteria
Project documents are located and available on Github Pages.

### Tasks 
1. - [ ] Add project concept and description.

**Comment by kh0ma** [comment]
According to GitHub pages documentation creating a page is possible only for personal or organizational profiles. But it is not possible to do so for one particular project within an organization. I'm closing it as "Will not fix".

![image.png](https://images.zenhubusercontent.com/5f7b73516450e01e28e9899e/2800c569-b114-48a8-9885-3fc87072aa4f)
